spring.application.name=bunMart

server.port=6001
grpc.server.port=9001

spring.datasource.url=jdbc:postgresql://localhost:5442/bunmart_auth
spring.datasource.username=bunmart
spring.datasource.password=bunmart_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=BunMartSecretKey2026SuperSecureKeyThatIsLongEnoughForHS256Algorithm
jwt.expiration=86400000

