spring.application.name=bunMart
grpc.server.port=9092

spring.datasource.url=jdbc:postgresql://localhost:5432/kitchenDB
spring.datasource.username=postgres
spring.datasource.password=665544
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# gRPC client ? calls Order Service to notify when production is completed
grpc.client.orderService.address=static://localhost:9091
grpc.client.orderService.negotiationType=PLAINTEXT