spring.application.name=kitchenService
grpc.server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5433/kitchenDB
spring.datasource.username=bunmart
spring.datasource.password=bunmart_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true