spring.application.name=kitchenService
server.port=6008
grpc.server.port=9006

spring.datasource.url=jdbc:postgresql://localhost:5433/kitchenDB
spring.datasource.username=bunmart
spring.datasource.password=bunmart_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# gRPC client: notification service (notify user when order sent to kitchen / prepared)
grpc.client.notificationService.address=static://localhost:9007
grpc.client.notificationService.negotiationType=plaintext
grpc.client.notificationService.enable-keep-alive=true

# gRPC client: order service (update order status to PREPARED when kitchen completes)
grpc.client.orderService.address=static://localhost:9004
grpc.client.orderService.negotiationType=plaintext
grpc.client.orderService.enable-keep-alive=true