spring.application.name=reviewService
server.port=8089
grpc.server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5440/bunmart_review
spring.datasource.username=bunmart
spring.datasource.password=bunmart_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true