spring.application.name=notificationService
server.port=6009
grpc.server.port=9007

spring.datasource.url=jdbc:postgresql://localhost:5439/bunmart_notification
spring.datasource.username=bunmart
spring.datasource.password=bunmart_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
