spring.application.name=paymentService
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5437/bunmart_payment
spring.datasource.username=bunmart
spring.datasource.password=bunmart_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true