# name of this service - used in logs
spring.application.name=payment-service

# REST port - frontend calls http://localhost:8084
server.port=8084

# sql server connection
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bunmart_payment;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=YOUR_PASSWORD_HERE
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# update = jpa creates the payments table automatically on first run
# never use create-drop in production - it deletes data on restart
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# grpc port - order service calls grpc://localhost:9094
grpc.server.port=9094
grpc.server.security.enabled=false

# other services grpc addresses - payment service calls these
grpc.client.order-service.address=static://localhost:9091
grpc.client.order-service.negotiation-type=plaintext

grpc.client.notification-service.address=static://localhost:9098
grpc.client.notification-service.negotiation-type=plaintext

# stripe test keys - get from stripe.com -> developers -> api keys
# sk_test_ = test mode, no real money charged, works in sri lanka
stripe.api.key=sk_test_YOUR_KEY_HERE


# get this by running: stripe listen --forward-to localhost:8084/api/webhooks/stripe
stripe.webhook.secret=whsec_YOUR_SECRET_HERE