spring.application.name=bunMart
server.port=6007
grpc.server.port=9005

spring.datasource.url=jdbc:postgresql://localhost:5434/bunmart_pricing
spring.datasource.username=bunmart
spring.datasource.password=bunmart_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true