spring.application.name=orderManagementService
server.port=6005
grpc.server.port=9004

spring.datasource.url=jdbc:postgresql://localhost:5436/bunmart_order
spring.datasource.username=bunmart
spring.datasource.password=bunmart_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# gRPC client: cart service (remove items from cart after order is placed)
grpc.client.cartService.address=static://localhost:9003
grpc.client.cartService.negotiationType=plaintext
grpc.client.cartService.enable-keep-alive=true

# gRPC client: notification service (notify user when order shipped)
grpc.client.notificationService.address=static://localhost:9007
grpc.client.notificationService.negotiationType=plaintext
grpc.client.notificationService.enable-keep-alive=true
