spring.application.name=orderManagementService
grpc.server.port=9080


spring.datasource.url=jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


grpc.client.cartService.address=static://localhost:9090
grpc.client.cartService.negotiationType=plaintext

grpc.client.pricingService.address=static://localhost:9070
grpc.client.pricingService.negotiationType=plaintext

grpc.client.paymentService.address=static://localhost:9060
grpc.client.paymentService.negotiationType=plaintext

grpc.client.kitchenService.address=static://localhost:9050
grpc.client.kitchenService.negotiationType=plaintext

grpc.client.shippingService.address=static://localhost:9040
grpc.client.shippingService.negotiationType=plaintext

grpc.client.notificationService.address=static://localhost:9030
grpc.client.notificationService.negotiationType=plaintext
