spring.application.name=orderManagementService
grpc.server.port=9080

spring.datasource.url=jdbc:mysql://localhost:3306/bunmart_orders?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# gRPC client addresses 
grpc.client.cartService.address=static://localhost:9090
grpc.client.cartService.negotiationType=plaintext

grpc.client.pricingService.address=static://localhost:9070
grpc.client.pricingService.negotiationType=plaintext

grpc.client.paymentService.address=static://localhost:9060
grpc.client.paymentService.negotiationType=plaintext

grpc.client.kitchenService.address=static://localhost:9050
grpc.client.kitchenService.negotiationType=plaintext

grpc.client.shippingService.address=static://localhost:9040
grpc.client.shippingService.negotiationType=plaintext

grpc.client.notificationService.address=static://localhost:9030
grpc.client.notificationService.negotiationType=plaintext
