spring.application.name=orderManagementService
grpc.server.port=9080

spring.mongodb.uri=mongodb+srv://Nuwan:Nuwan@mydatabase.pkuddyo.mongodb.net/MyDatabase?retryWrites=true&w=majority

# gRPC client addresses
grpc.client.cartService.address=static://localhost:9090
grpc.client.cartService.negotiationType=plaintext

grpc.client.pricingService.address=static://localhost:9070
grpc.client.pricingService.negotiationType=plaintext

grpc.client.paymentService.address=static://localhost:9060
grpc.client.paymentService.negotiationType=plaintext

grpc.client.kitchenService.address=static://localhost:9050
grpc.client.kitchenService.negotiationType=plaintext

grpc.client.shippingService.address=static://localhost:9040
grpc.client.shippingService.negotiationType=plaintext

grpc.client.notificationService.address=static://localhost:9030
grpc.client.notificationService.negotiationType=plaintext
